### ISSUE TITLE
Add Video Delete Button

### ISSUE THREAD

**Issue by Danushka96** [Danushka96/VotablePlayer#1]
Add Video Delete button for the user that added the song in to the play list.

**Comment by rahul1995** [comment]
Can I work on this one?

**Comment by Danushka96** [comment]
Sure. If there any problem let me know.

**Comment by leandrodma** [comment]
https://github.com/Danushka96/VotablePlayer/pull/2

**Comment by Danushka96** [comment]
Ok thank you @leandrodma. 👍

**Comment by rahul1995** [comment]
@Danushka96 @leandrodma this is not a good treat. Seems like I wasted my time. :/

**Comment by rahul1995** [comment]
@ppkavinda  Should show a confirmation dialog box on clicking delete button instead of deleting item immediately.

**Comment by Danushka96** [comment]
@rahul1995 really sorry rahul, My mistake, Won't happen again

**Comment by leandrodma** [comment]
@rahul1995 Man, really so sorry. My mistake, I had seen the issue and did not warn to @Danushka96.  But, send your PR man, i know that @Danushka96 will sees it also. Best Regrats

**Comment by rahul1995** [comment]
@leandrodma @Danushka96  It's okay. I'm feeling bad now.
