### ISSUE TITLE
Avoid adding duplicate songs

### ISSUE THREAD

**Issue by ppkavinda** [Danushka96/VotablePlayer#4]
when adding new songs to the playlist, check and avoid duplicates

**Comment by btzr-io** [comment]
I'll work on this one or at least try :stuck_out_tongue:

**Comment by rahul1995** [comment]
I'm also trying on this one.

**Comment by Danushka96** [comment]
@rahul1995 This one is yours 👍

**Comment by rahul1995** [comment]
@Danushka96  I think @btzr-io should try this. I might not get time on weekdays. I'll still try to be active on this repo

**Comment by Danushka96** [comment]
@rahul1995 Thanks for your interest on this repo. Hope you'll be in touch with us.

**Comment by Danushka96** [comment]
@btzr-io Hey buddy, You can continue work on this.
